name: CI Testing
on:
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']
jobs:
  lint-api: 
    name: 'Lint API tests folder'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: check node
        run: node -v
      - name: Install dependecies
        working-directory: ./lesson-14
        run: npm i
      - name: Run lint
        working-directory: ./lesson-14
        run: npm run lint
  lint-pw: 
    name: 'Lint PW tests folder'
    runs-on: ubuntu-latest
    container:
      image: node:22-slim 
    steps:
      - uses: actions/checkout@v4
      - name: check node
        run: node -v
      - name: Install dependecies
        working-directory: ./lesson-30
        run: npm i
      - name: Run lint
        working-directory: ./lesson-30
        run: npm run lint
  tests-api: 
    name: 'API tests Jest'
    if: ${{ always() }}
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependecies
        working-directory: ./lesson-14
        run: npm i
      - name: Run api test
        working-directory: ./lesson-14
        run: npm run test
  tests-pw-custom-image: 
    name: 'PW e2e tests on custom image'
    if: ${{ always() }}
    needs: lint-pw
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./lesson-30
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./lesson-30
        run: npx playwright install --with-deps 
      - name: Run e2e tests
        working-directory: ./lesson-30
        run: npm run test:headed:chromium
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        working-directory: ./lesson-30
        with:
          name: playwright-report-custom
          path: |
                playwright-report/
                test-results/
          retention-days: 30
  tests-pw-default-image: 
    name: 'PW e2e tests on default image'
    needs: tests-pw-custom-image
    runs-on: ubuntu-latest
    container:
     image: mcr.microsoft.com/playwright:v1.52.0
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./lesson-30
        run: npm ci
      - name: Run e2e tests
        working-directory: ./lesson-30
        run: |
              npm run test:headed:chrome:grep:settings-fixture
              npm run test:headed:chrome:grep:settings-setup
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        working-directory: ./lesson-30
        with:
          name: playwright-report-custom
          path: |
                playwright-report/
                test-results/
          retention-days: 30