name: CI Testing
on:
  # schedule:
  #  - cron: '* * * * *'
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']
jobs:
  lint-api: 
    name: 'Lint API tests folder'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: check node
        run: node -v
      - name: Install dependecies
        working-directory: ./lesson-14
        run: npm i
      - name: Run lint
        working-directory: ./lesson-14
        run: npm run lint
  tests-api: 
    name: 'API tests Jest'
    if: ${{ always() }}
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependecies
        working-directory: ./lesson-14
        run: npm i
      - name: Run api test
        working-directory: ./lesson-14
        run: npm run test